# Generated by Django 4.1.7 on 2023-03-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu name')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('href', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('named_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Named URL')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.parent', verbose_name='Related menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.parent', verbose_name='Parent')),
            ],
            options={
                'ordering': ['menu', 'id'],
            },
        ),
    ]
